### ISSUE TITLE
Stuck on "getting channel history..."

### ISSUE THREAD

**Issue by o2dazone** [wee-slack/wee-slack#858] opened 2022-02-16 22:31 UTC
Weechat 3.4
wee-slack version https://github.com/wee-slack/wee-slack/commit/76c1d0977b528e2030e02693b2e11de54ac4d44a
MacOS Monterey on Apple Silicon

This issue appeared after upgrading to Monterey from Big Sur. I can see the debug URLs making calls out to the API, and I can view them, but the buffer just shows "getting channel history..."

`plugins.var.python.slack.background_load_all_history` is `false`
`plugins.var.python.slack.thread_messages_in_channel` is also `false`

from `0` level debug logs

```
DEBUG: RECEIVED FROM QUEUE 
DEBUG: stored context <snip> https://api.slack.com/api/rtm.start?batch_presence_aware=1&mpim_aware=true&token=<token>
DEBUG: RECEIVED CALLBACK with request of rtm.start id of e32f59151ce7e78f492dbd3bb13da99b71575d28 and code -1 of length 65536
DEBUG: RECEIVED CALLBACK with request of rtm.start id of e32f59151ce7e78f492dbd3bb13da99b71575d28 and code -1 of length 65536 
DEBUG: RECEIVED CALLBACK with request of rtm.start id of e32f59151ce7e78f492dbd3bb13da99b71575d28 and code -1 of length 65536
DEBUG: RECEIVED CALLBACK with request of rtm.start id of e32f59151ce7e78f492dbd3bb13da99b71575d28 and code -1 of length 65536 
DEBUG: RECEIVED CALLBACK with request of rtm.start id of e32f59151ce7e78f492dbd3bb13da99b71575d28 and code -1 of length 65536
DEBUG: RECEIVED CALLBACK with request of rtm.start id of e32f59151ce7e78f492dbd3bb13da99b71575d28 and code -1 of length 65536 
DEBUG: RECEIVED CALLBACK with request of rtm.start id of e32f59151ce7e78f492dbd3bb13da99b71575d28 and code -1 of length 65536 
```

This goes on for quite a while, followed by

```
DEBUG: stored context E49PWUDKAZ6K91518I100YMTY8AOOLYUKV4ZBYPA https://api.slack.com/api/conversations.info?channel=C02J47G0G&token=<token>
DEBUG: stored context G9T8FIGKC67G6OT2DL3XIQU80WP6Z4BLAKV0U98A https://api.slack.com/api/conversations.info?channel=C02T9EU3M&token=<token>
DEBUG: stored context BB5HAUMTPZ1K7D9Z94HV9VG9O0ZQ1XOJY6K39SC2 https://api.slack.com/api/conversations.info?channel=C0ANVTPAS&token=<token>
DEBUG: stored context Z20AUUPKSKQJ368KDHIHV9ONIRSGM5UQIRQW9PJK https://api.slack.com/api/conversations.info?channel=C0GKTNP36&token=<token>
DEBUG: stored context TN7W2GS9P5Z0DA72EOHKEKFT37S9MSBC8UYLC2JO https://api.slack.com/api/conversations.info?channel=C1660P3U7&token=<token>
DEBUG: stored context T2C6YN2KUT1BQYDE4XAOYH5DTPLJTZOS3AZ2ZI7E https://api.slack.com/api/conversations.info?channel=C2HHR4N7N&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.info id of 6088ec3e15507cdbacda32bfccbb40d9275245ff and code -2 of length 0
DEBUG: RECEIVED FROM QUEUE 
DEBUG: stored context XPYIDIRQNH6SHZI1TNHJ845MYQKXCC2C2YKGAIJU https://api.slack.com/api/conversations.info?channel=C72Q7QBPE&token=<token>
DEBUG: stored context 7RAY0CUTT9UR2E7P7474BBFSA6J4KGSDX8WR73UU https://api.slack.com/api/conversations.info?channel=C75P2QCKY&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.info id of 1bb8dbc23e91d028f1163576d8affc111b2a1d70 and code -2 of length 0
DEBUG: RECEIVED CALLBACK with request of conversations.info id of b404757637e59a43f2fd91216b5203f2b02508e0 and code -2 of length 0 
DEBUG: stored context 1DHTHTHVUMUAGXGQ9FA50M3MELTBXCHIFZ8NEGGD https://api.slack.com/api/conversations.info?channel=C7C5RBK1R&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.info id of 76db8585d648a5a7c8fd17109a069f30935d626f and code -2 of length 0
DEBUG: stored context YRT3L2DYZ277234EHB8SNKTSPNWI9AI5QGGYX70D https://api.slack.com/api/conversations.info?channel=C89GXK9F1&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.info id of 3c1df6aca46b670fee9beba192153a194ffd3f14 and code -2 of length 0 
DEBUG: stored context 5KPQKEZZ30MAGHL5Z1LE3Y51S1005ZIJ9QMEEA4Z https://api.slack.com/api/conversations.info?channel=C8NLB4G74&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.info id of 9b7e5323e87fde813fd0aa815fab8c182e64349b and code -2 of length 0
DEBUG: stored context CVIAEVQPFSBMUSJEUP6ZNBAPO8OJ6VVUW5VTXCCD https://api.slack.com/api/conversations.info?channel=C9DA1EKL3&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.info id of bc00a6626c84fce31179a34f8f385042ac76a96e and code -2 of length 0 
DEBUG: stored context S6MFQ3XSFLGWY7FRMR7TIYD1QWUIY6F5XTH6RFIK https://api.slack.com/api/conversations.info?channel=CA11H0W7M&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.info id of 5a3a86f14575f6e8ec964fca2bf5c9983b3c2931 and code -2 of length 0
DEBUG: stored context 1CW19L0K7BI23JHWAPWGXOZ6VR16RSIPRO6LJ5VQ https://api.slack.com/api/conversations.info?channel=CBYPWRU72&token=<token>
```

and then

```
DEBUG: RECEIVED CALLBACK with request of conversations.members id of f0cb8a6ee721b636501747049872340cd00f2a9f and code -2 of length 0
DEBUG: RECEIVED CALLBACK with request of conversations.members id of 47417a25488b17ff07d456a4c6cc05c55f1110fa and code -2 of length 0
DEBUG: RECEIVED CALLBACK with request of conversations.members id of 4b8320a714e6ac46b0a7052838c95b1d74b06cf1 and code -2 of length 0
DEBUG: RECEIVED CALLBACK with request of conversations.members id of d980ad37f6eb02132e1da1944babf604774acc91 and code -2 of length 0
DEBUG: RECEIVED CALLBACK with request of conversations.members id of ccd247644e0e412292a85f3da2990cd52c95585b and code -2 of length 0
DEBUG: RECEIVED CALLBACK with request of conversations.history id of 0e117bb423eb18703cb57173b6cd4bc109df6bfa and code -2 of length 0
DEBUG: RECEIVED CALLBACK with request of conversations.history id of 2b2e2d2c357400015e394641cee0d2e6b657c9d4 and code -2 of length 0
DEBUG: RECEIVED FROM QUEUE 
DEBUG: RECEIVED FROM QUEUE 
DEBUG: SET FROM type 
DEBUG: running presence_change
DEBUG: RECEIVED FROM QUEUE 
DEBUG: RECEIVED FROM QUEUE 
DEBUG: RECEIVED FROM QUEUE 
DEBUG: RECEIVED FROM QUEUE
```

and more

```
DEBUG: SET FROM type 
DEBUG: running presence_change
DEBUG: RECEIVED CALLBACK with request of conversations.history id of 2948a1d869c74f591f252c2ea3918d942950b7f1 and code -2 of length 0
DEBUG: SET FROM type 
DEBUG: running presence_change
DEBUG: SET FROM type 
DEBUG: running presence_change
DEBUG: SET FROM type 
DEBUG: running presence_change
DEBUG: SET FROM type 
DEBUG: running presence_change
DEBUG: from slow queue
DEBUG: stored context 34K8ZRUUM9VTJGNKOB4S907DF2TXOR0CEVSP8UOX https://api.slack.com/api/conversations.history?channel=G018NF8T78A&count=200&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.history id of 89a18e82f61a9299894acf5885d1e484f0cf2b0f and code -2 of length 0
DEBUG: from slow queue
DEBUG: stored context SHTUWGPIH64V90PZT6W8VWHC3QMUN3C5G351JZGF https://api.slack.com/api/conversations.history?channel=G018MSA659U&count=200&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.history id of d3082b1b25e2470dc8f9eccff6d8354a0a4faca7 and code -2 of length 0
DEBUG: from slow queue
DEBUG: stored context LOP4UI37R8OAZI2YYRNL11NKTVEQXGRQEV8YCNTU https://api.slack.com/api/conversations.history?channel=G0144R31CPL&count=200&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.history id of 175fcf29875e5276971ec831a9989c003eb790fb and code -2 of length 0
DEBUG: from slow queue
DEBUG: stored context DVHBH54LAIWQ9C8ZFVAUF8ZV2ZZ8Z7CTGCA77HGV https://api.slack.com/api/conversations.history?channel=G012THMCJGM&count=200&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.history id of afbe45a70c3f307ae834ce9f3203e6c4c062d7b5 and code -2 of length 0
DEBUG: RECEIVED FROM QUEUE 
DEBUG: SET FROM type 
DEBUG: running presence_change
DEBUG: from slow queue
DEBUG: stored context BV13AQC2G39IDRYFVW8A0T6AH5ARCCAPNITBRYHC https://api.slack.com/api/conversations.history?channel=G0128T8RYBD&count=200&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.history id of 81eecb77077872e49723e66dd5de276be76f657c and code -2 of length 0
DEBUG: from slow queue 



DEBUG: stored context Z5YTISYJBQJFI2PYXG4AQOY2II7105QZWNTH08OB https://api.slack.com/api/conversations.history?channel=C026K97BSNN&count=200&token=<token>
DEBUG: RECEIVED CALLBACK with request of conversations.history id of b2fa009418a068aaba74b1085d61a248f084aff5 and code -2 of length 0
DEBUG: RECEIVED FROM QUEUE 
DEBUG: SET FROM type 
DEBUG: running file_public 
DEBUG: Callback not implemented for event: file_public 
DEBUG: RECEIVED FROM QUEUE 
DEBUG: SET FROM type 
DEBUG: running file_shared 
DEBUG: Callback not implemented for event: file_shared 
DEBUG: from slow queue
```

**Comment by trygveaa** [comment] 2022-02-16 22:37
I suspect this is the same issue as https://github.com/weechat/weechat/issues/1723. Could you try running `export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES` before starting weechat as suggested in that issue?

**Comment by o2dazone** [comment] 2022-02-16 22:48
Wow interesting, yup that fixes it. It does seem to take a considerable amount more time fetching channels (especially ones with really long histories). I assume `OBJC_DISABLE_INITIALIZE_FORK_SAFETY` disables some sort of multithreading within Python, which explains the slightly longer time to fetch channel history?

Odd that it's related to the scripts. I also had this problem, as my `~/.weechat/scripts/plugins.xml.gz` was empty. I ended up manually downloading it from https://weechat.org/files/plugins.xml.gz, and overriding the zero bit binary to get it working

**Comment by trygveaa** [comment] 2022-02-16 23:01
Sorry, I don't know anything about how this affects performance, though it does sound strange to me that it would make it slower.

So since the issue is in WeeChat and wee-slack just uses WeeChat's API to request URLs I'll close this issue. As you can see, the WeeChat issue is stuck on the maintainer needing more info. Feel free to comment here if you want even if it's closed though.

**Comment by o2dazone** [comment] 2022-02-16 23:01
Thanks for your speedy help on this @trygveaa

**Closed by trygveaa** 2022-02-16 23:01 UTC
