### ISSUE TITLE
Are we ready for conversations API?

### ISSUE THREAD

**Issue by AmlingHexagon** [wee-slack/wee-slack#826] opened 2021-02-12 19:56 UTC
[1] says they're gonna break a whole bunch of APIs including `channels`, `im`, `mpim`, and `groups` in favor of the new `conversations` API.  Are we ready for this?  I still see what look like such API methods in the source as of `8bd734c8e9a6`.

[1] https://api.slack.com/changelog/2020-01-deprecating-antecedents-to-the-conversations-api

**Comment by trygveaa** [comment] 2021-02-20 12:24
Closing as a duplicate of #792.

**Closed by trygveaa** 2021-02-20 12:24 UTC

**Comment by AmlingHexagon** [comment] 2021-02-22 17:40
(oh my shame)

**Comment by trygveaa** [comment] 2021-02-22 17:45
No problem :) I was rather late on fixing it.
