### ISSUE TITLE
Weeslack crashes with key error message

### ISSUE THREAD

**Issue by disassembler** [wee-slack/wee-slack#454] opened 2017-10-11 19:32 UTC
I've been using weeslack for a week and after restarting weechat today, I get this error on startup:

```
                │1525 │ python: stdout/stderr: Traceback (most recent call last):
                  │1525 │ python: stdout/stderr:   File "/home/sam/.weechat/python/autoload/wee_slack.py", line 484, in handle_next
                  │1525 │ python: stdout/stderr:     EVENTROUTER.handle_next()
                  │1525 │ python: stdout/stderr:   File "/home/sam/.weechat/python/autoload/wee_slack.py", line 472, in handle_next
                  │1525 │ python: stdout/stderr:     self.handlers[function_name](j, self, **kwargs)
                  │1525 │ python: stdout/stderr:   File "/home/sam/.weechat/python/autoload/wee_slack.py", line 2083, in handle_rtmstart
                  │1525 │ python: stdout/stderr:     channels[item["id"]] = SlackDMChannel(eventrouter, users, **item)
                  │1525 │ python: stdout/stderr:   File "/home/sam/.weechat/python/autoload/wee_slack.py", line 1575, in __init__
                  │1525 │ python: stdout/stderr:     kwargs["name"] = users[dmuser].name
                  │1525 │ python: stdout/stderr: KeyError: u'U09TF41GT'
```

**Comment by disassembler** [comment] 2017-10-11 19:59
FYI this fixes the issue and I can use wee-slack again, although it's super hacky: https://github.com/wee-slack/wee-slack/compare/master...disassembler:ignore-broken-dmchannels?expand=1

**Comment by trygveaa** [comment] 2017-10-11 20:15
This seems like the same error as the first in #361, do you use enterprise grid? Would be useful to know if this error message is caused by that or not.

Could you report the contents of the `users` and `kwargs` variables when this happens? I.e. print them in the else block in that patch, sensor any sensitive information and paste it here?

**Comment by disassembler** [comment] 2017-10-12 01:01
This isn't enterprise grid, it's hosted slack, but I do have a shared channel (which looks to be the bad one by this output) that might be enterprise grid, I'm not sure.

```
 u'name': u'MASKED', u'email_domain': u'MASKED', u'has_compliance_export': False, u'id': u'T027WTVUZ', u'icon': {u'image_230':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_132.jpg', u'image_132':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_132.jpg', u'image_68':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_68.jpg', u'image_original':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_original.jpg', u'image_34':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_34.jpg', u'image_102':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_102.jpg', u'image_44':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_44.jpg', u'image_88':
 u'https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_88.jpg'}}}], u'id': u'D7CQDUH7A',
 u'is_org_shared': False, u'is_open': False, u'user': u'U09TF41GT', u'is_im': True, u'is_ext_shared': True, u'has_pins': False}
 python: stdout/stderr: {u'U7GBNJQ01': Name:MASKED Identifier:U7GBNJQ01, u'U7EDSH05D': Name:MASKED Identifier:U7EDSH05D, u'U7CBHUQTY':
 Name:MASKED Identifier:U7CBHUQTY, u'U7E8JT5RU': Name:MASKED Identifier:U7E8JT5RU, u'U7GT72GCC': Name:MASKED Identifier:U7GT72GCC,
 u'U7B9S26KS': Name:MASKED Identifier:U7B9S26KS, u'U7C0FPWSJ': Name:MASKED Identifier:U7C0FPWSJ, u'U7B4243LJ': Name:MASKED
 Identifier:U7B4243LJ, u'U7C102803': Name:MASKED Identifier:U7C102803, u'USLACKBOT': Name:slackbot Identifier:USLACKBOT, u'U7G7N7E2C':
 Name:MASKED Identifier:U7G7N7E2C, u'U78EB08S1': Name:MASKED Identifier:U78EB08S1, u'U7H4MNT0D': Name:MASKEDIdentifier:U7H4MNT0D,
 u'U7EP8JJKU': Name:MASKED Identifier:U7EP8JJKU, u'U7BAYDHNZ': Name:MASKED Identifier:U7BAYDHNZ, u'U7C6CK1MM': Name:MASKED Identifier:U7C6CK1MM
 u'U7ELYD799': Name:MASKED Identifier:U7ELYD799, u'U7HUN6Y4X': Name:MASKED Identifier:U7HUN6Y4X, u'U7AHAC1G8': Name:MASKED
 Identifier:U7AHAC1G8, u'U7HU6CB1V': Name:MASKED Identifier:U7HU6CB1V, u'U7ARB1KBP': Name:MASKED Identifier:U7ARB1KBP, u'U76HYRSG3':
 Name:MASKED Identifier:U76HYRSG3, u'U7C0V8LES': Name:MASKED Identifier:U7C0V8LES, u'U7C3RQHGE': Name:MASKED Identifier:U7C3RQHGE,
 u'U7H0FSC5B': Name:MASKED Identifier:U7H0FSC5B, u'U79AU3M39': Name:MASKED Identifier:U79AU3M39, u'U7C0LP97G': Name:MASKED
 Identifier:U7C0LP97G, u'U7B7WB7LM': Name:MASKED Identifier:U7B7WB7LM, u'U7FRQ7FAB': Name:MASKED Identifier:U7FRQ7FAB, u'U7611MYMN': Name:MASKED
 Identifier:U7611MYMN, u'U7B7DCDT6': Name:MASKED Identifier:U7B7DCDT6, u'U7HUCH0GP': Name:MASKED Identifier:U7HUCH0GP, u'U7C0QKVSS': Name:MASKED
 Identifier:U7C0QKVSS, u'U7GAPK75X': Name:MASKED Identifier:U7GAPK75X, u'U7GB9CYTB': Name:MASKED Identifier:U7GB9CYTB, u'U7B422M7C':
 Name:MASKED
 Identifier:U7B422M7C}

```

**Comment by realdavidops** [comment] 2017-10-12 01:03
@disassembler Slack admin here - the other end of the shared channel is not enterprise grid.

**Comment by trygveaa** [comment] 2017-10-12 06:17
Ah, it's a shared channel (or a DM with a user on another team, I guess?). That makes sense, as we wouldn't have the username of that user.

I guess we need to make a request get info about the user. Unless it included above what you pasted? It seems a bit cut off (has fire } and one ], but only three {). Could you check if there are any other references to `U09TF41GT` in the response to `rtm.start` (the `login_data` variable in `handle_rtmstart`)?

**Comment by disassembler** [comment] 2017-10-12 13:10
This looks to be the problem channel in the channels array:
```
        {                                                                                                                                                                 
            "created": 1507136504,                                                                                                                                        
            "creator": "U027WTVV5",                                                                                                                                       
            "has_pins": false,                                                                                                                                            
            "id": "C7DC7P94J",                                                                                                                                            
            "is_archived": false,                                                                                                                                         
            "is_channel": true,                                                                                                                                           
            "is_general": false,                                                                                                                                          
            "is_member": true,                                                                                                                                            
            "is_mpim": false,                                                                                                                                             
            "is_org_shared": false,                                                                                                                                       
            "is_private": false,                                                                                                                                          
            "is_shared": true,                                                                                                                                            
            "last_read": "1507746181.000476",                                                                                                                             
            "members": [                                                                                                                                                  
                "U027WTVV5",                                                                                                                                              
                "U027YRCRU",                                                                                                                                              
                "U09TF41GT",                                                                                                                                              
                "U7611MYMN",                                                                                                                                              
                "U764VU5QQ",                                                                                                                                              
                "U7C6CK1MM",                                                                                                                                              
                "U7DBTS5HR"                                                                                                                                               
            ],                                                                                                                                                            
            "name": "my-channel-name",                                                                                                                                      
            "name_normalized": "my-channel-name",                                                                                                                           
            "previous_names": [                                                                                                                                           
                "old-channel-name"                                                                                                                                           
            ],                                                                                                                                                            
            "priority": 0.061042468788241,                                                                                                                                
            "purpose": {                                                                                                                                                  
                "creator": "",                                                                                                                                            
                "last_set": 0,                                                                                                                                            
                "value": ""                                                                                                                                               
            },                                                                                                                                                            
            "shared_team_ids": [                                                                                                                                          
                "T027WTVUZ"                                                                                                                                               
            ],                                                                                                                                                            
            "topic": {                                                                                                                                                    
                "creator": "",                                                                                                                                            
                "last_set": 0,                                                                                                                                            
                "value": ""                                                                                                                                               
            },
            "unlinked": 0                                                                                                                                                 
        }
```

Another match is here (ims array):
```
        {                                                                                                                                                                 
            "created": 1507142190,                                                                                                                                        
            "has_pins": false,                                                                                                                                            
            "id": "D7CQDUH7A",                                                                                                                                            
            "is_ext_shared": true,                                                                                                                                        
            "is_im": true,                                                                                                                                                
            "is_open": false,                                                                                                                                             
            "is_org_shared": false,                                                                                                                                       
            "is_shared": true,                                                                                                                                            
            "last_read": "1507142222.000240",                                                                                                                             
            "priority": 0.022996476829878,                                                                                                                                
            "shares": [                                                                                                                                                   
                {                                                                                                                                                         
                    "date_create": "1507142190",                                                                                                                          
                    "id": "T027WTVUZ",                                                                                                                                    
                    "is_active": true,                                                                                                                                    
                    "name": "Other Company",                                                                                                                                     
                    "team": {                                                                                                                                             
                        "domain": "othercompany",                                                                                                                               
                        "email_domain": "othercompany.com",                                                                                                                     
                        "has_compliance_export": false,                                                                                                                   
                        "icon": {                                                                                                                                         
                            "image_102": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_102.jpg",                    
                            "image_132": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_132.jpg",                    
                            "image_230": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_132.jpg",                    
                            "image_34": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_34.jpg",                      
                            "image_44": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_44.jpg",                      
                            "image_68": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_68.jpg",                      
                            "image_88": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_88.jpg",                      
                            "image_original": "https://slack-files2.s3-us-west-2.amazonaws.com/avatars/2015-07-28/8312036695_44eeba3e7737eacaf0ee_original.jpg"           
                        },                                                                                                                                                
                        "id": "T027WTVUZ",                                                                                                                                
                        "name": "Other Company"                                                                                                                                  
                    }                                                                                                                                                     
                }                                                                                                                                                         
            ],                                                                                                                                                            
            "user": "U09TF41GT"                                                                                                                                           
        }
```

**Comment by auscompgeek** [comment] 2018-05-31 13:29
@benjaminwood See #462.

**Comment by benjaminwood** [comment] 2018-05-31 14:14
Awesome, thanks for the direction @auscompgeek

Cheers! 🍻

**Comment by trygveaa** [comment] 2018-07-06 06:32
This is now fixed.

**Closed by trygveaa** 2018-07-06 06:32 UTC
