### ISSUE TITLE
Large messages don't displayed

### ISSUE THREAD

**Issue by dzfweb** [wee-slack/wee-slack#385] opened 2017-07-07 16:16 UTC
I'm using wee-slack, and everything seems to be ok, but i'm get a problem with large messages not being displayed.

![screenshot_232](https://user-images.githubusercontent.com/10212321/27966666-69cfbe46-6316-11e7-973d-3be1dfebc883.png)

![screenshot_231](https://user-images.githubusercontent.com/10212321/27966640-4e83344c-6316-11e7-8566-6af484ddf9f2.png)

I'm using inside bash on Windows 10, WeeChat 1.9.

**Comment by dzfweb** [comment] 2017-07-07 16:22
** UPDATE **
The problem occurs only when the message has a line break.


![screenshot_233](https://user-images.githubusercontent.com/10212321/27966892-51a6591e-6317-11e7-9a12-97689a0a0aa1.png)
![screenshot_234](https://user-images.githubusercontent.com/10212321/27966893-51a6d9f2-6317-11e7-9f7f-c4e244cf56ec.png)

**Comment by dzfweb** [comment] 2017-07-07 21:02
**UPDATE**
The error occurs only in private messages, the same message is displayed normally inside a channel

**Comment by denibertovic** [comment] 2017-07-07 21:04
I've seen this happen when somebody sends a snippet as well. If I close weechat and go back to fetch the history the snippet displays fine within the "```" delimiters.

**Comment by dzfweb** [comment] 2017-07-07 21:05
Exactly. If i reload weechat the message is displayed normally too, but no when i received it.

**Comment by denibertovic** [comment] 2017-07-07 22:11
I wonder if just doing `/python reload slack` would work as well.

**Comment by dzfweb** [comment] 2017-07-07 23:01
That is what i'm doing when i need it

**Comment by auscompgeek** [comment] 2017-07-07 23:06
Guessing the multiline message handling is different in each buffer type (which it _really_ shouldn't be). Sounds simple enough to fix.

**Comment by dzfweb** [comment] 2017-07-07 23:09
I'm trying to find in the code to fix, if someone know and want to help, it would be really helpful

**Comment by dzfweb** [comment] 2017-07-08 00:11
fixed and created a PR #https://github.com/wee-slack/wee-slack/pull/386

**Comment by trygveaa** [comment] 2017-09-22 14:23
This is a duplicate of #274, so I'm closing this in favor of that. I have created a PR (#439) which hopefully fixes the issue without altering the behavior for users that don't experience the bug. Please test it and report if it fixes the problem or not.

**Closed by trygveaa** 2017-09-22 14:23 UTC
