### ISSUE TITLE
Multiline messages are shown as python | channel-name

### ISSUE THREAD

**Issue by antoyo** [wee-slack/wee-slack#332] opened 2017-04-11 14:20 UTC
Hello.
When I receive a multiline message it shows as such:

> username | Test
> python | org.slack.com.channel
> python | org.slack.com.channel
> python | org.slack.com.channel

instead of the usual:

> username | Test
> username | Multi
> username | Line
> username | Message

If I leave and open again WeeChat, I see the multiline message correctly.

Thanks to fix this issue.

**Comment by V13Axel** [comment] 2017-04-11 17:51
I've seen reports that this is fixed in [wee-ng](https://github.com/wee-slack/wee-ng). 

Have you tried using it instead?

**Comment by V13Axel** [comment] 2017-04-11 17:52
This is also a duplicate of #274

**Closed** 2017-04-11 18:00 UTC

**Comment by dzfweb** [comment] 2017-07-07 16:44
i'm having this problem, and the https://github.com/wee-slack/wee-ng don't exists.
