### ISSUE TITLE
Missing online markers on direct chats

### ISSUE THREAD

**Issue by LinkedList** [wee-slack/wee-slack#488] opened 2018-01-16 09:16 UTC
Hi, I've been using wee-slack for over a year now and it always worked great.
I don't know what happened but suddenly now none of my direct chats show the '+' marker that the person is online even thought they are online (see image).
I didn't change any settings and didn't even update the plugin.

![onlineoffline](https://user-images.githubusercontent.com/1116349/34980723-a0fb8356-faa5-11e7-8455-30cd4ec761b0.png)

**Comment by V13Axel** [comment] 2018-01-17 16:23
Looks like it's just presences in general not working. Users aren't showing up under the here/away headers either:
![presences_not_working](https://user-images.githubusercontent.com/2779682/35053681-d0756c0e-fb78-11e7-9859-14d52a161fa5.png)

**Comment by trygveaa** [comment] 2018-01-17 16:30
Probably caused by this (though it says the change happened November 15 last year): https://api.slack.com/changelog/2017-10-making-rtm-presence-subscription-only

**Comment by trygveaa** [comment] 2018-01-27 12:00
This is now fixed with PR #496.

**Closed by trygveaa** 2018-01-27 12:00 UTC
