### ISSUE TITLE
No thread shown after a reply to an image

### ISSUE THREAD

**Issue by er-1** [wee-slack/wee-slack#658] opened 2018-11-06 13:25 UTC
After someone uploaded an image, if there are replies, there is no thread id (nor thread messages).
In slack app:
![slack](https://user-images.githubusercontent.com/14091680/48066935-3183c800-e1cf-11e8-931a-9d56f78f8c45.png)

In weechat: 
![wee_slack](https://user-images.githubusercontent.com/14091680/48066949-41031100-e1cf-11e8-96ba-5d43a5f5ae37.png)

**Comment by trygveaa** [comment] 2018-11-06 15:22
Hm, I can't reproduce this. Can you enable debug mode and see if there is any output in the core buffer when someone replies to the thread? If not, can you check the debug buffer (which is created when you enable debug mode).

Enable debug mode by running:
```
/set plugins.var.python.slack.debug_level 0
/set plugins.var.python.slack.debug_mode true
```

**Comment by trygveaa** [comment] 2019-01-26 23:17
Closing since I can't reproduce the issue, and the poster didn't answer.

**Closed by trygveaa** 2019-01-26 23:17 UTC
