### ISSUE TITLE
Crash on weechat exit

### ISSUE THREAD

**Issue by rjarry** [wee-slack/wee-slack#922] opened 2024-02-05 10:45 UTC
Hi,

I am getting this crash when exiting weechat with `slack.py` installed.

```
======= WeeChat backtrace =======
(written by WeeChat 4.1.2, compiled on Dec  4 2023 00:00:00)
001  ??:0 [function ??]
002  ??:0 [function ??]
003  ??:? [function __restore_rt]
004  ??:? [function PyObject_GC_UnTrack]
005  ??:? [function PyGC_Collect]
006  ??:? [function _PyObject_FastCallDictTstate]
007  ??:? [function PyObject_Free]
008  ??:? [function _PyModule_ClearDict]
009  ??:? [function PyGC_Collect]
010  ??:? [function Py_EndInterpreter]
011  ??:? [function weechat_python_load]
012  ??:? [function weechat_python_load]
013  ??:? [function plugin_script_action_install]
014  ??:? [function weechat_python_signal_script_action_cb]
015  ??:0 [function ??]
016  ??:0 [function ??]
017  ??:0 [function ??]
018  ??:0 [function ??]
019  ??:? [function __libc_start_call_main]
020  :? [function __libc_start_main_alias_2]
021  ??:0 [function ??]
======= End of  backtrace =======
```

Here is some info about the python version involved:

```
$ ldd /usr/lib64/weechat/plugins/python.so 
	linux-vdso.so.1 (0x00007ffe957d9000)
	libpython3.12.so.1.0 => /lib64/libpython3.12.so.1.0 (0x00007f9353400000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f935321e000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f9353af9000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f9353c35000)
```

Any idea what could be wrong?

**Comment by trygveaa** [comment] 2024-02-20 22:26
This is perhaps the same as this issue? https://github.com/weechat/weechat/issues/2046

There is apparently some issue with Python 3.12 in WeeChat. Not sure what the cause is yet.

**Comment by trygveaa** [comment] 2024-03-08 19:40
This looks to be the same issue as the one I linked to, so I'll close this. If this issue still occurs after that one is fixed, feel free to reopen or post a new issue.

The stack trace is a bit different though (and different from the one you posted in that issue, which is similar to the one I get). It seems like you've managed to trigger it when installing a script somehow. If you have a way to reproduce that, I would be interested.

**Closed by trygveaa** 2024-03-08 19:40 UTC
