### ISSUE TITLE
privatized channel broken

### ISSUE THREAD

**Issue by carnott-snap** [wee-slack/wee-slack#693] opened 2019-05-29 00:16 UTC
I have a channel that was `#channel` and got privatized. I expected it to show up as `&channel`, but it still is listed as `#channel`, and while I can post messages, fetching history is broken. Debug logs do not show any failures, even at level 0, but I may be missing something.

**Comment by trygveaa** [comment] 2019-05-29 06:17
Duplicate of #664.

**Closed by trygveaa** 2019-05-29 06:17 UTC
