### ISSUE TITLE
Tagging/mentioning users with same nick

### ISSUE THREAD

**Issue by cvincent** [wee-slack/wee-slack#673] opened 2019-02-07 22:28 UTC
I'm in a Slack workspace where two people have the same nick. Something like:

Real name: `Bob Smith`; Nick: `Bob`
Real name: `Bob Doe`; Nick: `Bob`

When tagging Bob with `@Bob`, Slack may tag the wrong Bob. I discovered this when I got this message back from slackbot:

`You mentioned @Bob, but they're not in this private channel.`

When I checked the Slack web app, my message had indeed tagged the wrong Bob, who was not in that channel. When I run `/whois Bob`, I get back only the Bob that was mistakenly tagged.

It seems strange that multiple people could be allowed to have the same nick, but that appears to be the case here.

**Comment by trygveaa** [comment] 2019-04-26 10:27
Closing as a duplicate of #685 (newer issue, but it's a bit broader and has some discussion).

**Closed by trygveaa** 2019-04-26 10:27 UTC
