### ISSUE TITLE
Blockquote in Messages

### ISSUE THREAD

**Issue by gisu** [wee-slack/wee-slack#421] opened 2017-08-09 09:30 UTC
If a user use blockquotes in the Message, inside wee-slack i saw only a `python` Message. 

![image](https://user-images.githubusercontent.com/442468/29114923-05ed9ade-7cf6-11e7-902d-3c02e7dfdbf4.png)

**Comment by dzfweb** [comment] 2017-08-29 17:59
i've create a PR with a solution for this problem #https://github.com/wee-slack/wee-slack/pull/386

**Comment by trygveaa** [comment] 2017-09-22 14:23
This is a duplicate of #274, so I'm closing this in favor of that. I have created a PR (#439) which hopefully fixes the issue without altering the behavior for users that don't experience the bug. Please test it and report if it fixes the problem or not.

**Closed by trygveaa** 2017-09-22 14:23 UTC
