### ISSUE TITLE
cannot send messages

### ISSUE THREAD

**Issue by carnott-snap** [wee-slack/wee-slack#798] opened 2020-10-05 20:23 UTC
Recently I lost the ability to send messages to channels, users, or bots. I can still emoji react and receive message, both from others and myself (via the slack web app), but when I try to send a message it never shows up in weechat or the slack webapp. When I enabled debugging, I see the following:
```
DEBUG: test
DEBUG: Sent {"type": "message", "channel": "REDACTED", "text": "test", "user": "REDACTED", "id": 3}...
```

**Comment by trygveaa** [comment] 2020-10-05 20:24
Duplicate of #797. It's a error on Slacks side, see https://status.slack.com/.

**Closed by trygveaa** 2020-10-05 20:24 UTC

**Comment by carnott-snap** [comment] 2020-10-05 20:28
weird that did not show up when I looked at open issues just 20m ago, sorry for the hassle
