### ISSUE TITLE
[Feature request] just thread in another buffer

### ISSUE THREAD

**Issue by guyfedwards** [wee-slack/wee-slack#851] opened 2021-08-18 10:26 UTC
I don't know if this is already possible and I have missed it somehow but currently my flow is something like:
- get notification in slack main buffer
- notification tells me there is a response in a thread in another channel
- switch to the other channel while trying to remember the id of the thread
- `/thread <id>` to join

What I'm wondering/proposing is the ability to join directly from the main buffer either with just the thread id or with the channel first.
E.g.
```
# in main channel buffer
New message in thread 9ac, channel &general to which you are subscribed
/thread general/3er
```

**Comment by trygveaa** [comment] 2021-08-18 10:48
Duplicate of #762.

**Closed by trygveaa** 2021-08-18 10:48 UTC
Labels: duplicate
