### ISSUE TITLE
python: error in function "receive_ws_callback"

### ISSUE THREAD

**Issue by Strykar** [wee-slack/wee-slack#837] opened 2021-05-01 14:00 UTC
`wee-slack` (2.7.0) appears to work just fine in spite of these messages on Arch.
The issue started after the [weechat-matrix](https://github.com/poljar/weechat-matrix) (0.2.0) plugin was enabled to use.

It logs this to the weechat (3.1.2) buffer:
```
19:23 python: stdout/stderr (slack): Traceback (most recent call last):
19:23 python: stdout/stderr (slack):   File "/home/strykar/weechat-greatest/python/autoload/wee_slack.py", line 167, in wrapper
19:23 python: stdout/stderr (slack):     return f(*decode_from_utf8(args), **decode_from_utf8(kwargs))
19:23 python: stdout/stderr (slack):   File "/home/strykar/weechat-greatest/python/autoload/wee_slack.py", line 579, in receive_ws_callback
19:23 python: stdout/stderr (slack):     handle_socket_error(e, team, 'receive')
19:23 python: stdout/stderr (slack):   File "/home/strykar/weechat-greatest/python/autoload/wee_slack.py", line 574, in receive_ws_callback
19:23 python: stdout/stderr (slack):     opcode, data = team.ws.recv_data(control_frame=True)
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 376, in recv_data
19:23 python: stdout/stderr (slack):     opcode, frame = self.recv_data_frame(control_frame)
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 395, in recv_data_frame
19:23 python: stdout/stderr (slack):     frame = self.recv_frame()
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 431, in recv_frame
19:23 python: stdout/stderr (slack):     return self.frame_buffer.recv_frame()
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_abnf.py", line 372, in recv_frame
19:23 python: stdout/stderr (slack):     self.recv_header()
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_abnf.py", line 320, in recv_header
19:23 python: stdout/stderr (slack):     header = self.recv_strict(2)
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_abnf.py", line 407, in recv_strict
19:23 python: stdout/stderr (slack):     bytes_ = self.recv(min(16384, shortage))
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_core.py", line 514, in _recv
19:23 python: stdout/stderr (slack):     return recv(self.sock, bufsize)
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/site-packages/websocket/_socket.py", line 111, in recv
19:23 python: stdout/stderr (slack):     bytes_ = sock.recv(bufsize)
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/ssl.py", line 1226, in recv
19:23 python: stdout/stderr (slack):     return self.read(buflen)
19:23 python: stdout/stderr (slack):   File "/usr/lib/python3.9/ssl.py", line 1101, in read
19:23 python: stdout/stderr (slack):     return self._sslobj.read(len)
19:23 python: stdout/stderr (slack): ssl.SSLWantReadError: The operation did not complete (read) (_ssl.c:2627)
19:23 =!= python: error in function "receive_ws_callback"
```
Unsure if it's related to https://github.com/wee-slack/wee-slack/issues/812

**Comment by trygveaa** [comment] 2021-05-01 22:30
Yes, this is a duplicate of #812.

**Closed by trygveaa** 2021-05-01 22:30 UTC
Labels: duplicate
