### ISSUE TITLE
It seems session tokens ceased to work

### ISSUE THREAD

**Issue by oblitum** [wee-slack/wee-slack#849] opened 2021-08-05 21:08 UTC
Today I couldn't login on any of the teams I used to join for a long time. When trying to obtain new session tokens, they didn't work on weechat, which just returned "ERROR: Failed connecting to Slack with token xoxc-6981808421...a4946e748e: invalid_auth". So it seems [session tokens](https://github.com/wee-slack/wee-slack#get-a-session-token) are gone for good?... It's sad because it was the only usable way to use wee-slack for me, simply can't request N teams to add wee-slack to authorize it for oauth method..

**Comment by trygveaa** [comment] 2021-08-05 21:18
Duplicate of #844.

xoxs-tokens seem to be gone for good (though, the ones I currently use still work). It seems like we can add support for xoxc-tokens, but it takes some work.

**Closed by trygveaa** 2021-08-05 21:18 UTC
