### ISSUE TITLE
All threads (ever?) open when starting weechat/wee-slack

### ISSUE THREAD

**Issue by ecksun** [wee-slack/wee-slack#803] opened 2020-10-10 19:21 UTC
Hi,

When I start weechat, or reload wee-slack (`/python reload slack`) many threads (~70) open. I have read and closed all those threads in the past.

If I close them all (`/buffer close ..`) and reload wee-slack again they appear once more.

This started happening recently, possibly after I upgraded to wee-slack 2.6.0 (from 2.4 or 2.5, I'm not entirely sure).

For completeness sake, here are my settings:

```
plugins.var.python.slack.auto_open_threads                   string   "true"
plugins.var.python.slack.background_load_all_history         string   "true"
plugins.var.python.slack.channel_name_typing_indicator       string   "true"
plugins.var.python.slack.color_buflist_muted_channels        string   "darkgray"
plugins.var.python.slack.color_deleted                       string   "red"
plugins.var.python.slack.color_edited_suffix                 string   "095"
plugins.var.python.slack.color_reaction_suffix               string   "darkgray"
plugins.var.python.slack.color_reaction_suffix_added_by_you  string   "blue"
plugins.var.python.slack.color_thread_suffix                 string   "lightcyan"
plugins.var.python.slack.color_typing_notice                 string   "yellow"
plugins.var.python.slack.colorize_attachments                string   "prefix"
plugins.var.python.slack.colorize_private_chats              string   "false"
plugins.var.python.slack.debug_level                         string   "0"
plugins.var.python.slack.debug_mode                          string   "on"
plugins.var.python.slack.distracting_channels                string   ""                                                                                            
plugins.var.python.slack.external_user_suffix                string   "*"
plugins.var.python.slack.files_download_location             string   "%h/slack_downloads/"
plugins.var.python.slack.group_name_prefix                   string   "&"
plugins.var.python.slack.history_fetch_count                 string   "200"
plugins.var.python.slack.map_underline_to                    string   "_"
plugins.var.python.slack.migrated                            string   "true"
plugins.var.python.slack.muted_channels_activity             string   "personal_highlights"
plugins.var.python.slack.never_away                          string   "true"
plugins.var.python.slack.notify_subscribed_threads           string   "auto"
plugins.var.python.slack.notify_usergroup_handle_updated     string   "true"
plugins.var.python.slack.record_events                       string   "false"
plugins.var.python.slack.render_bold_as                      string   "bold"
plugins.var.python.slack.render_emoji_as_string              string   "true"
plugins.var.python.slack.render_italic_as                    string   "italic"
plugins.var.python.slack.send_typing_notice                  string   "false"
plugins.var.python.slack.server_aliases                      string   ""                                                                                            
plugins.var.python.slack.shared_name_prefix                  string   "%"
plugins.var.python.slack.short_buffer_names                  string   "false"
plugins.var.python.slack.show_buflist_presence               string   "true"
plugins.var.python.slack.show_reaction_nicks                 string   "true"
plugins.var.python.slack.slack_timeout                       string   "20000"
plugins.var.python.slack.switch_buffer_on_join               string   "true"
plugins.var.python.slack.thread_messages_in_channel          string   "true" 
plugins.var.python.slack.unfurl_auto_link_display            string   "text"
plugins.var.python.slack.unfurl_ignore_alt_text              string   "false"
plugins.var.python.slack.unhide_buffers_with_activity        string   "false"
plugins.var.python.slack.use_full_names                      string   "false" 
```

**Comment by trygveaa** [comment] 2020-10-11 15:41
I assume you use an [OAuth token](https://github.com/wee-slack/wee-slack#get-a-token-with-oauth) and not a [session token](https://github.com/wee-slack/wee-slack#get-a-session-token)? The problem is that when using an OAuth token there is no way to mark a thread as read. Since you have `auto_open_threads` on all unread threads will be opened when the script loads, which since no threads are marked as read will be all threads.

It seems that the reason it didn't happen with 2.5.0 is that we used the `last_read` time of the channel instead of the `last_read` time of the thread to check if the thread should be opened. Maybe we should still do that when using an OAuth token.

**Comment by ecksun** [comment] 2020-10-11 20:34
> I assume you use an OAuth token and not a session token? 

I'm not sure (was a while ago I configured wee-slack). How can I check?

Is it possible to switch without re-configuring all the things?

> The problem is that when using an OAuth token there is no way to mark a thread as read.

Aha, okay, I see.

> Since you have auto_open_threads on all unread threads will be opened when the script loads, which since no threads are marked as read will be all threads.

Alright, so this is "expected behavior" then, by some definition of "expected" :)

> It seems that the reason it didn't happen with 2.5.0 is that we used the last_read time of the channel instead of the last_read time of the thread to check if the thread should be opened. Maybe we should still do that when using an OAuth token.

While that might not be entirely correct it is probably less surprising than threads accumulating forever. Would probably be more annoying if you start weechat when you start your computer.

**Comment by trygveaa** [comment] 2020-10-11 22:15
> > I assume you use an OAuth token and not a session token?
> 
> I'm not sure (was a while ago I configured wee-slack). How can I check?

If the token starts with `xoxp` it's an OAuth token, if it starts with `xoxs` it's a session token.

> Is it possible to switch without re-configuring all the things?

Yes, just replace the token in `slack_api_token`.

**Comment by ecksun** [comment] 2020-10-25 22:28
Thanks!

Replacing it seems to have improved things, however I'm not sure it completely solved the issue.

I changed the token and reloaded slack (`/python reload slack`) and a bunch of threads showed up. I then went through all of them and ran `/buffer close`. Then I reloaded again and new threads showed up (though much fewer). I did the same again and yet more threads showed up (fewer still).

If I check in the web-ui there are still `9+` unread threads.

When are threads marked as read?

**Comment by mtbc** [comment] 2021-07-22 13:23
#830 suggests,

> Only threads with mentions created after starts are opened in separate buffers

Something like this might be nice if I could set some idea of only *recent* threads, e.g., those with latest activity no more than 24h before start.

> ... just replace the token ...

Hmmm, just change the prefix, or get a new token somehow?

**Closed** 2023-09-30 22:32 UTC

**Comment by trygveaa** [comment] 2023-09-30 22:44
It looks like the issue here may have been that some threads that one isn't subscribed to was opened by `auto_open_threads` (if the thread had a WeeChat highlight, or contained `@channel` or `@here`). Only threads that one is subscribed to can be marked as read, so that caused the thread to be opened every time. Now only threads one is subscribed to is opened automatically.

Hopefully this was the issue, but feel free to comment or open a new issue if there's still problems.

Note that it's still a problem with OAuth tokens as mentioned above, it only works with session tokens. I recommend disabling `auto_open_threads` if OAuth tokens is used.

And sorry I missed the questions here and didn't answer. If still useful, here are the answers:

> When are threads marked as read?

They are marked as read when you switch away from the buffer and when you run `/buffer set unread` (or `/input set_unread_current_buffer` for WeeChat < 3.8).

> Hmmm, just change the prefix, or get a new token somehow?

You have to get a different token as described here: https://github.com/wee-slack/wee-slack#get-a-session-token
