### ISSUE TITLE
Thread command not working in Weechat relay

### ISSUE THREAD

**Issue by Phyks** [wee-slack/wee-slack#615] opened 2018-08-22 13:45 UTC
Hi,

I'm a wee-slack user and a heavy user of weechat relay (typically with https://github.com/ubergeek42/weechat-android). I noticed that the `/thread` command is never interpreted when I'm using a relay.

I did not find any extra info about it in the doc, so not sure if this is somehow expected or not. Tested with both Weechat-Android and Glowing-Bear, so I guess this is not an issue coming from my relay client app.

Is the `/thread` command supposed to work across a weechat relay?

Thanks!

**Comment by trygveaa** [comment] 2018-08-22 20:26
This might be related to #547. What happens when you try to use the `/thread` command?

I haven't looked into it, so I'm not sure if it's caused by a bug in wee-slack or a limitation in the relay client. As far as I know, the relay doesn't support edits though, so I'm not sure where you're getting the thread ids from? Are you only using the ones that are printed when loading the plugin?

**Comment by Phyks** [comment] 2018-08-22 21:18
Indeed, I get the same output so it's likely to be the same issue. Sorry I missed this one :/ Feel free to close this one and continue in #547 then.

Concerning the thread ids, sure it's not the best usability as relay does not support edit. Still, by closing and reopening buffers, Weechat for Android refetches the whole content of the buffer and it seems to be getting the updated content in this case. This means that one can force refresh the buffers and get the thread ids this way. My main use case is that I often start discussion in threads through the Slack web interface and forget to open them in my Weechat before leaving my laptop. Then, I can easily find the thread id on my mobile, but cannot open the thread buffer to continue discussion on the go :/

By the way, not related, but is there a way to force wee-slack to show buffers as unread when new messages are  added in threads (ie mark it as unread whenever a message has been posted either in reply to the channel or in a thread under this channel)? This would be some really helpful feature for me which is sadly not offered by Slack interface itself :(

Thanks!

**Comment by trygveaa** [comment] 2018-11-04 23:43
This has now been fixed.

> By the way, not related, but is there a way to force wee-slack to show buffers as unread when new messages are added in threads (ie mark it as unread whenever a message has been posted either in reply to the channel or in a thread under this channel)?

You want a buffer to be shown as unread without any new messages in it? That's not available, but there was recently added an option for showing thread messages in the channel they belong to (`thread_messages_in_channel`). Since this makes thread messages printed in the channel, the channel will be marked as unread.

**Closed by trygveaa** 2018-11-04 23:43 UTC

**Comment by Phyks** [comment] 2018-11-05 07:59
> This has now been fixed.

Awesome, thanks a lot! I'll try the latest version right away.

> You want a buffer to be shown as unread without any new messages in it? That's not available, but there was recently added an option for showing thread messages in the channel they belong to (thread_messages_in_channel). Since this makes thread messages printed in the channel, the channel will be marked as unread.

That's exactly what I was looking for, thanks!
